FROM node:18-bullseye

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --legacy-peer-deps --force

# Копируем весь код
COPY . .

# Открываем порт dev-сервера  Vite dev-server по умолчанию на 5173
EXPOSE 5173  
# Если хочешь через 8080 — можно в package.json менять или через --port

# Команда запуска dev-сервера
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
# CMD ["npm", "run", "dev"]
