# Stage 1: build
FROM node:18-bullseye AS build
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Чистая установка зависимостей
RUN npm install --legacy-peer-deps --force

# Копируем весь код
COPY . .

# Сборка Vite проекта
RUN npm run build

# Stage 2: production
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
